import type { ScanResult } from '../core/types.js';
import type { BundleFile, BundleOptions, DiagramKind } from './bundle.js';
import { basename } from 'node:path';

const USECVIS_MODE: Record<DiagramKind, string> = {
  'attack-tree': '0',
  'privilege-gradient': '6',
  component: '7',
};

const DIAGRAM_LABELS: Record<DiagramKind, string> = {
  'attack-tree': 'Attack Tree',
  'privilege-gradient': 'Privilege Gradient',
  component: 'Component Diagram',
};

export function generateBundleReadme(
  result: ScanResult,
  files: BundleFile[],
  options: BundleOptions,
): string {
  const lines: string[] = [];
  lines.push('# VASO Visualization Bundle');
  lines.push('');
  lines.push(`Scan timestamp: ${result.timestamp}`);
  lines.push(`Host: ${result.host ?? 'local'}`);
  lines.push(`Score: ${result.totalScore}/100 (${result.totalGrade})`);
  lines.push(`Format: ${options.format}`);
  lines.push('');

  lines.push('## Files');
  lines.push('');
  for (const f of files.filter(f => f.diagram !== 'readme')) {
    lines.push(`- \`${basename(f.path)}\` — ${DIAGRAM_LABELS[f.diagram as DiagramKind]} (${f.bytes} bytes)`);
  }
  lines.push('');

  lines.push('## Render with USecVisLib');
  lines.push('');
  lines.push('Install: https://github.com/vulnex/usecvislib');
  lines.push('');
  lines.push('```bash');
  for (const f of files.filter(f => f.diagram !== 'readme')) {
    const mode = USECVIS_MODE[f.diagram as DiagramKind];
    const name = basename(f.path);
    const out = name.replace(/\.[a-z]+$/, '');
    lines.push(`usecvis -m ${mode} -i ${name} -o ${out} -f png`);
  }
  lines.push('```');
  lines.push('');

  lines.push('## Note on CVSS scores');
  lines.push('');
  lines.push('Attack-tree leaves carry a `cvss` value. The source is one of:');
  lines.push('');
  lines.push('- **Real CVSS** — extracted from advisory check evidence when a CVE reference includes a numeric score.');
  lines.push('- **Severity-mapped** — coarse approximation when no real CVSS is available:');
  lines.push('  - `critical` → 9.0');
  lines.push('  - `warning` → 5.0');
  lines.push('  - `info` → 2.0');
  lines.push('');
  lines.push('Severity-mapped values exist to drive USecVisLib\'s color presets. Treat them as severity bands, not real CVSS measurements.');
  lines.push('');

  lines.push('---');
  lines.push('Generated by `vaso visualize` (VULNEX Agent Security Observer).');

  return lines.join('\n') + '\n';
}
