import { checkRegistry } from '../core/check-registry.js';
import { configChecks } from './config/index.js';
import { skillChecks } from './skills/index.js';
import { iocChecks } from './ioc/index.js';
import { networkChecks } from './network/index.js';
import { runtimeChecks } from './runtime/index.js';
import { mcpChecks } from './mcp/index.js';
import { openclawChecks } from './openclaw/index.js';
import { nanoclawChecks } from './nanoclaw/index.js';
import { ironclawChecks } from './ironclaw/index.js';
import { nanobotChecks } from './nanobot/index.js';
import { zeroclawChecks } from './zeroclaw/index.js';
import { lyrieChecks } from './lyrie/index.js';
import { policyChecks } from './policy/index.js';
import { advisoryChecks } from './advisory/index.js';
import { claudeCodeChecks } from './claude-code/index.js';
import { codexChecks } from './codex/index.js';
import { opencodeChecks } from './opencode/index.js';
import { geminiCliChecks } from './gemini-cli/index.js';
import { qwenCodeChecks } from './qwen-code/index.js';
import { cursorCliChecks } from './cursor-cli/index.js';
import { copilotCliChecks } from './copilot-cli/index.js';

export function registerAllChecks(): void {
  checkRegistry.registerAll(configChecks);
  checkRegistry.registerAll(skillChecks);
  checkRegistry.registerAll(iocChecks);
  checkRegistry.registerAll(networkChecks);
  checkRegistry.registerAll(runtimeChecks);
  checkRegistry.registerAll(mcpChecks);
  checkRegistry.registerAll(openclawChecks);
  checkRegistry.registerAll(nanoclawChecks);
  checkRegistry.registerAll(ironclawChecks);
  checkRegistry.registerAll(nanobotChecks);
  checkRegistry.registerAll(zeroclawChecks);
  checkRegistry.registerAll(lyrieChecks);
  checkRegistry.registerAll(policyChecks);
  checkRegistry.registerAll(advisoryChecks);
  checkRegistry.registerAll(claudeCodeChecks);
  checkRegistry.registerAll(codexChecks);
  checkRegistry.registerAll(opencodeChecks);
  checkRegistry.registerAll(geminiCliChecks);
  checkRegistry.registerAll(qwenCodeChecks);
  checkRegistry.registerAll(cursorCliChecks);
  checkRegistry.registerAll(copilotCliChecks);
}
