import { readFile, writeFile, mkdir, unlink, chmod, access } from 'node:fs/promises';
import { join, dirname } from 'node:path';
import { homedir } from 'node:os';
import { execFileSync } from 'node:child_process';
import type { PluginAgentType, PluginConfig, PluginManifest, PluginInfo } from './types.js';
import { PLUGIN_AGENTS, DEFAULT_PLUGIN_CONFIG } from './types.js';

const VERSION = '0.2.1';

const PLUGIN_PATHS: Record<PluginAgentType, string> = {
  openclaw: join(homedir(), '.openclaw', 'plugins', 'vaso-security.mjs'),
  nanoclaw: join(homedir(), '.config', 'nanoclaw', 'plugins', 'vaso-security.mjs'),
  picoclaw: join(homedir(), '.picoclaw', 'plugins', 'vaso-security.mjs'),
};

const CONFIG_PATH = join(homedir(), '.vaso', 'plugin-config.json');

export function getPluginInstallPath(agent: PluginAgentType): string {
  return PLUGIN_PATHS[agent];
}

function getManifestPath(agent: PluginAgentType): string {
  const pluginPath = getPluginInstallPath(agent);
  return join(dirname(pluginPath), 'vaso-plugin-manifest.json');
}

export function resolveVasoBinaryPath(): string {
  // Try process.argv[1] (the script being run)
  if (process.argv[1]) {
    return process.argv[1];
  }

  // Try `which vaso`
  try {
    const result = execFileSync('which', ['vaso'], { encoding: 'utf-8' }).trim();
    if (result) return result;
  } catch {
    // not found
  }

  // Fallback
  return 'vaso';
}

export function generatePluginContent(agent: PluginAgentType, vasoBinaryPath: string): string {
  const configPath = CONFIG_PATH;

  const sharedPreamble = `// VASO Security Plugin — auto-generated by vaso plugin install
// Do not edit manually. Re-run: vaso plugin install --agent ${agent} --force
import { execFileSync } from 'node:child_process';
import { readFileSync } from 'node:fs';

const VASO_BINARY = ${JSON.stringify(vasoBinaryPath)};
const VASO_VERSION = ${JSON.stringify(VERSION)};
const CONFIG_PATH = ${JSON.stringify(configPath)};

function loadConfig() {
  try {
    const raw = readFileSync(CONFIG_PATH, 'utf-8');
    return { blockOnCritical: true, blockOnWarning: false, timeout: 30000, excludeChecks: [], ...JSON.parse(raw) };
  } catch {
    return { blockOnCritical: true, blockOnWarning: false, timeout: 30000, excludeChecks: [] };
  }
}

function runScan(agent) {
  const config = loadConfig();
  try {
    const stdout = execFileSync(VASO_BINARY, ['scan', '--agent', agent, '--format', 'json'], {
      timeout: config.timeout,
      encoding: 'utf-8',
      stdio: ['pipe', 'pipe', 'pipe'],
    });
    return JSON.parse(stdout);
  } catch (err) {
    // Exit code 1 means critical findings — stdout still has valid JSON
    if (err.stdout) {
      try { return JSON.parse(err.stdout); } catch { /* fall through */ }
    }
    console.warn('[vaso] Security scan failed, allowing startup:', err.message);
    return null;
  }
}

function evaluate(result, config) {
  if (!result) return { blocked: false };
  const critical = result.agents?.flatMap(a => a.results ?? [])
    .filter(r => r.severity === 'critical' && !r.passed && !config.excludeChecks.includes(r.id)) ?? [];
  const warnings = result.agents?.flatMap(a => a.results ?? [])
    .filter(r => r.severity === 'warning' && !r.passed && !config.excludeChecks.includes(r.id)) ?? [];

  if (config.blockOnCritical && critical.length > 0) {
    return { blocked: true, reason: critical.length + ' critical finding(s)', critical, warnings };
  }
  if (config.blockOnWarning && warnings.length > 0) {
    return { blocked: true, reason: warnings.length + ' warning finding(s)', critical, warnings };
  }
  return { blocked: false, critical, warnings };
}
`;

  if (agent === 'openclaw') {
    return `${sharedPreamble}
export default {
  name: 'vaso-security',
  version: VASO_VERSION,
  hooks: {
    before_agent_start: async () => {
      const result = runScan('openclaw');
      const config = loadConfig();
      const evaluation = evaluate(result, config);
      if (evaluation.warnings?.length) {
        console.warn('[vaso] ' + evaluation.warnings.length + ' security warning(s) detected');
      }
      if (evaluation.blocked) {
        throw new Error('[vaso] Agent startup blocked: ' + evaluation.reason);
      }
    },
  },
};
`;
  }

  if (agent === 'nanoclaw') {
    return `${sharedPreamble}
export const name = 'vaso-security';
export const version = VASO_VERSION;
export const lifecycle = {
  onBeforeStart: async () => {
    const result = runScan('nanoclaw');
    const config = loadConfig();
    const evaluation = evaluate(result, config);
    if (evaluation.warnings?.length) {
      console.warn('[vaso] ' + evaluation.warnings.length + ' security warning(s) detected');
    }
    if (evaluation.blocked) {
      throw new Error('[vaso] Agent startup blocked: ' + evaluation.reason);
    }
  },
};
`;
  }

  // picoclaw
  return `${sharedPreamble}
export default {
  name: 'vaso-security',
  version: VASO_VERSION,
  handlers: {
    preStart: async () => {
      const result = runScan('picoclaw');
      const config = loadConfig();
      const evaluation = evaluate(result, config);
      if (evaluation.warnings?.length) {
        console.warn('[vaso] ' + evaluation.warnings.length + ' security warning(s) detected');
      }
      if (evaluation.blocked) {
        throw new Error('[vaso] Agent startup blocked: ' + evaluation.reason);
      }
    },
  },
};
`;
}

export interface InstallPluginOptions {
  force?: boolean;
  vasoBinaryPath?: string;
}

export async function installPlugin(
  agent: PluginAgentType,
  options?: InstallPluginOptions,
): Promise<{ pluginPath: string; manifestPath: string }> {
  const pluginPath = getPluginInstallPath(agent);
  const manifestPath = getManifestPath(agent);

  // Check existing
  if (!options?.force) {
    try {
      await access(pluginPath);
      throw new Error(`Plugin already installed at ${pluginPath}. Use --force to overwrite.`);
    } catch (err) {
      if ((err as NodeJS.ErrnoException).code !== 'ENOENT') throw err;
    }
  }

  const vasoBinaryPath = options?.vasoBinaryPath ?? resolveVasoBinaryPath();
  const content = generatePluginContent(agent, vasoBinaryPath);

  // Create directory
  await mkdir(dirname(pluginPath), { recursive: true });

  // Write plugin file
  await writeFile(pluginPath, content, 'utf-8');
  await chmod(pluginPath, 0o644);

  // Write manifest
  const manifest: PluginManifest = {
    agent,
    vasoVersion: VERSION,
    vasoBinaryPath,
    installedAt: new Date().toISOString(),
    pluginPath,
  };
  await writeFile(manifestPath, JSON.stringify(manifest, null, 2), 'utf-8');

  return { pluginPath, manifestPath };
}

export async function uninstallPlugin(agent: PluginAgentType): Promise<void> {
  const pluginPath = getPluginInstallPath(agent);
  const manifestPath = getManifestPath(agent);

  for (const filePath of [pluginPath, manifestPath]) {
    try {
      await unlink(filePath);
    } catch (err) {
      if ((err as NodeJS.ErrnoException).code !== 'ENOENT') throw err;
    }
  }
}

export async function getPluginStatus(agent?: PluginAgentType): Promise<PluginInfo[]> {
  const agents = agent ? [agent] : PLUGIN_AGENTS;
  const results: PluginInfo[] = [];

  for (const a of agents) {
    const pluginPath = getPluginInstallPath(a);
    const manifestPath = getManifestPath(a);

    let installed = false;
    let vasoBinaryPath: string | undefined;
    let installedAt: string | undefined;

    try {
      await access(pluginPath);
      installed = true;

      try {
        const raw = await readFile(manifestPath, 'utf-8');
        const manifest: PluginManifest = JSON.parse(raw);
        vasoBinaryPath = manifest.vasoBinaryPath;
        installedAt = manifest.installedAt;
      } catch {
        // manifest missing or corrupt — still installed
      }
    } catch {
      // not installed
    }

    results.push({
      agent: a,
      installed,
      pluginPath: installed ? pluginPath : undefined,
      vasoBinaryPath,
      installedAt,
    });
  }

  return results;
}

export async function loadPluginConfig(): Promise<PluginConfig> {
  try {
    const raw = await readFile(CONFIG_PATH, 'utf-8');
    const parsed = JSON.parse(raw);
    return { ...DEFAULT_PLUGIN_CONFIG, ...parsed };
  } catch {
    return { ...DEFAULT_PLUGIN_CONFIG };
  }
}

export async function savePluginConfig(config: PluginConfig): Promise<void> {
  await mkdir(dirname(CONFIG_PATH), { recursive: true });
  await writeFile(CONFIG_PATH, JSON.stringify(config, null, 2), 'utf-8');
}
