import { describe, it, expect } from 'vitest';
import { HtmlReporter } from './html.js';
import type { ScanResult } from '../core/types.js';

function makeScanResult(overrides?: Partial<ScanResult>): ScanResult {
  return {
    timestamp: '2026-02-21T12:00:00.000Z',
    agents: [{
      agent: 'openclaw',
      installation: {
        agent: 'openclaw',
        installDir: '/home/user/.openclaw',
        configFiles: [],
        user: 'testuser',
        profile: 'default',
      },
      results: [
        {
          id: 'CFG-001',
          name: 'Gateway Binding',
          category: 'config',
          severity: 'critical',
          passed: false,
          message: 'Gateway bound to 0.0.0.0',
          evidence: [{ file: '/home/user/.openclaw/config.yaml', line: 12 }],
          fixable: true,
          fixDescription: 'Bind to 127.0.0.1',
        },
        {
          id: 'CFG-003',
          name: 'TLS Disabled',
          category: 'config',
          severity: 'warning',
          passed: false,
          message: 'TLS is not enabled',
        },
        {
          id: 'CFG-005',
          name: 'Prompt Injection',
          category: 'config',
          severity: 'info',
          passed: false,
          message: 'Prompt injection detection not configured',
        },
        {
          id: 'CFG-002',
          name: 'API Key Exposure',
          category: 'config',
          severity: 'critical',
          passed: true,
          message: 'No API keys found in config',
        },
      ],
      score: 65,
      grade: 'C',
    }],
    totalScore: 65,
    totalGrade: 'C',
    summary: { critical: 1, warning: 1, info: 1, passed: 1, total: 4 },
    ...overrides,
  };
}

describe('HtmlReporter', () => {
  it('generates valid HTML structure', () => {
    const reporter = new HtmlReporter();
    const output = reporter.render(makeScanResult());

    expect(output).toContain('<!DOCTYPE html>');
    expect(output).toContain('<html lang="en">');
    expect(output).toContain('<head>');
    expect(output).toContain('<body>');
    expect(output).toContain('</html>');
    expect(output).toContain('<style>');
  });

  it('contains report content with score, grade, and timestamp', () => {
    const reporter = new HtmlReporter();
    const output = reporter.render(makeScanResult());

    expect(output).toContain('65/100');
    expect(output).toContain('Grade: C');
    expect(output).toContain('CFG-001');
    expect(output).toContain('2026-02-21T12:00:00.000Z');
    expect(output).toContain('VASO Security Scan Report');
  });

  it('renders severity levels with correct labels', () => {
    const reporter = new HtmlReporter();
    const output = reporter.render(makeScanResult());

    expect(output).toContain('critical');
    expect(output).toContain('warning');
    expect(output).toContain('info');
  });

  it('displays agent name when set', () => {
    const result = makeScanResult();
    result.agents[0].installation.agentName = 'my-agent';
    const reporter = new HtmlReporter();
    const output = reporter.render(result);

    expect(output).toContain('my-agent');
  });

  it('renders evidence with file paths and line numbers', () => {
    const reporter = new HtmlReporter();
    const output = reporter.render(makeScanResult());

    expect(output).toContain('/home/user/.openclaw/config.yaml');
    expect(output).toContain(':12');
  });

  it('escapes HTML special characters in messages', () => {
    const result = makeScanResult();
    result.agents[0].results[0].message = 'Value <script>alert("xss")</script> found';
    const reporter = new HtmlReporter();
    const output = reporter.render(result);

    expect(output).not.toContain('<script>');
    expect(output).toContain('&lt;script&gt;');
    expect(output).toContain('&quot;xss&quot;');
  });

  it('renders gracefully with no agents', () => {
    const result = makeScanResult({
      agents: [],
      totalScore: 100,
      totalGrade: 'A',
      summary: { critical: 0, warning: 0, info: 0, passed: 0, total: 0 },
    });
    const reporter = new HtmlReporter();
    const output = reporter.render(result);

    expect(output).toContain('<!DOCTYPE html>');
    expect(output).toContain('100/100');
    expect(output).toContain('Grade: A');
    expect(output).toContain('Generated by VASO');
  });

  it('shows fixable indication with fix description', () => {
    const reporter = new HtmlReporter();
    const output = reporter.render(makeScanResult());

    expect(output).toContain('Bind to 127.0.0.1');
  });

  it('shows passed checks in a list', () => {
    const reporter = new HtmlReporter();
    const output = reporter.render(makeScanResult());

    expect(output).toContain('Passed (1)');
    expect(output).toContain('CFG-002');
    expect(output).toContain('API Key Exposure');
  });

  it('includes user and profile metadata', () => {
    const reporter = new HtmlReporter();
    const output = reporter.render(makeScanResult());

    expect(output).toContain('testuser');
    expect(output).toContain('default');
  });

  it('has format property set to html', () => {
    const reporter = new HtmlReporter();
    expect(reporter.format).toBe('html');
  });
});
