import { describe, it, expect } from 'vitest';
import { MarkdownReporter } from './markdown.js';
import type { ScanResult } from '../core/types.js';

describe('MarkdownReporter', () => {
  it('generates markdown with headers and tables', () => {
    const result: ScanResult = {
      timestamp: '2026-02-20T00:00:00.000Z',
      agents: [{
        agent: 'openclaw',
        installation: { agent: 'openclaw', installDir: '/tmp', configFiles: [] },
        results: [
          {
            id: 'CFG-001',
            name: 'Gateway Binding',
            category: 'config',
            severity: 'critical',
            passed: false,
            message: 'Gateway bound to 0.0.0.0',
          },
          {
            id: 'CFG-002',
            name: 'API Key Exposure',
            category: 'config',
            severity: 'critical',
            passed: true,
            message: 'No API keys found',
          },
        ],
        score: 88,
        grade: 'B',
      }],
      totalScore: 88,
      totalGrade: 'B',
      summary: { critical: 1, warning: 0, info: 0, passed: 1, total: 2 },
    };

    const reporter = new MarkdownReporter();
    const output = reporter.render(result);

    expect(output).toContain('# VASO Security Scan Report');
    expect(output).toContain('**Score:** 88/100 (B)');
    expect(output).toContain('| CFG-001 |');
    expect(output).toContain('- **CFG-002**: API Key Exposure');
    expect(output).toContain('*Generated by VASO');
  });
});
