import type { ScanResult, Severity } from '../core/types.js';
import type { Reporter } from './reporter.js';

const SEVERITY_EMOJI: Record<Severity, string> = {
  critical: 'x',
  warning: '!',
  info: 'i',
};

export class MarkdownReporter implements Reporter {
  readonly format = 'markdown';

  render(result: ScanResult): string {
    const lines: string[] = [];

    lines.push('# VASO Security Scan Report');
    lines.push('');
    lines.push(`**Date:** ${result.timestamp}`);
    lines.push(`**Score:** ${result.totalScore}/100 (${result.totalGrade})`);
    lines.push(`**Agents scanned:** ${result.agents.length}`);
    lines.push('');

    lines.push('## Summary');
    lines.push('');
    lines.push(`| Severity | Count |`);
    lines.push(`|----------|-------|`);
    lines.push(`| Critical | ${result.summary.critical} |`);
    lines.push(`| Warning | ${result.summary.warning} |`);
    lines.push(`| Info | ${result.summary.info} |`);
    lines.push(`| Passed | ${result.summary.passed} |`);
    lines.push(`| **Total** | **${result.summary.total}** |`);
    lines.push('');

    for (const agent of result.agents) {
      const agentLabel = agent.installation.agentName
        ? `${agent.agent} (agent: ${agent.installation.agentName})`
        : agent.agent;
      lines.push(`## ${agentLabel} (Score: ${agent.score}, Grade: ${agent.grade})`);
      lines.push('');

      const failed = agent.results.filter(r => !r.passed);
      const passed = agent.results.filter(r => r.passed);

      if (failed.length > 0) {
        lines.push('### Findings');
        lines.push('');
        lines.push('| ID | Name | Severity | Message |');
        lines.push('|----|------|----------|---------|');
        for (const r of failed) {
          lines.push(`| ${r.id} | ${r.name} | ${r.severity} | ${r.message} |`);
        }
        lines.push('');
      }

      if (passed.length > 0) {
        lines.push(`### Passed (${passed.length})`);
        lines.push('');
        for (const r of passed) {
          lines.push(`- **${r.id}**: ${r.name}`);
        }
        lines.push('');
      }
    }

    lines.push('---');
    lines.push('*Generated by VASO (VULNEX Agent Security Observer)*');

    return lines.join('\n');
  }
}
